//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPPGrupoo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPago
    {
        public MetodoPago()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int MetodoPagoID { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CantidadDias { get; set; }
        public Nullable<bool> Dolar_US { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
